version: '3.8'
services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: unless-stopped
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - postgres:/data/postgres
        env_file:
            - .env
    api:
        container_name: api
        build: ./
        volumes:
            - .:/app
volumes:
    postgres:
    api: